# Streamlit configuration

[server]
headless = true
address = "0.0.0.0"
port = 5000

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4e89e8"
backgroundColor = "#0f1216"
secondaryBackgroundColor = "#171c23"
textColor = "#e0e0e0"
font = "sans serif"